config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :articles, only: [:index, :new, :create, :show, :edit, :update] do
    resources :comments, only: [:create]
  end
  # get '/articles/:article_id/comments', to: 'comments#index'

  # get '/articles', to: 'articles#index'
  # post '/articles', to: 'articles#create'
  get '/hello', to: 'hello#index'
  post '/hello', to: 'hello#say_hello'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  has_many :comments

  def self.search(keyword)
    where('title like ?', "%#{keyword}")
  end

  def self.recents
    order(created_at: :desc)
  end

  def self.title_order
    order(:title)
  end

  def self.ordering(mode)
    if mode == "0"
      title_order
    else
      recents
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true

  def self.authenticate(email, password)
    User.find_by(email: email, password: password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  def require_logged_in
    redirect_to login_path if current_user.blank?
  end

  helper_method :current_user
  def current_user
    user = User.find_by_id(session[:user_id])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_logged_in

    def index
        @articles = Article.search(params[:q]).ordering(params[:sort_mode])
        respond_to do |format|
            format.json { render json: @articles }
            format.html { render 'index' }
        end
      end

    def create
        @article = Article.new(article_params)
        # byebug
        if @article.save
            redirect_to articles_path
        else
            flash[:error] = 'Error: Cannot create new article'
            render 'new'
        end
    end

    def new
        @article = Article.new
    end

    def show
        @article = Article.find(params[:id])
        @comment = Comment.new
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        article = Article.find(params[:id])

        if article.update(article_params).present?
            redirect_to article_path(params[:id])
        else
            render 'edit'
        end
    end

    def article_params
        params.require(:article).permit(:title, :content)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_logged_in
  
  def create
    comment = Comment.new(comment_params)
    comment.article_id = params[:article_id]

    if comment.save
      redirect_to article_path(params[:article_id])
    else
      flash[:error] = "Error: Cannot create new comment"
      redirect_to article_path(params[:article_id])
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:name, :content)
  end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  before_action :require_logged_in
  
  def index
    @name = 'default'
  end

  def say_hello
    @name = params[:name]
    render 'index'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user.present?
      session[:user_id] = user.id
      redirect_to articles_path
    else
      flash[:error] = 'Invalid Email or Password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in
    current_user.present?
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Enter article title' %><br />
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control', placeholder: 'Enter your article content' %><br />
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/articles/edit.html.erb
<%= render "form" %>

app/views/articles/index.html.erb
<div class="container">
    <div class="row">
        <h1 class="page-header">Article Index</h1>
    </div>
    <div class="row">
        <%= link_to "New Article", new_article_path, class: 'btn btn-primary' %>
    </div>
    <div class="row">
      <%= form_tag articles_path, class: "form-inline", method: :get do %>
          <div class="form-group">
            <label for="">Keyword</label>
            <input type="text" class="form-control" name="q">
          </div>
          <div class="form-group">
            <label for="">Sort Mode</label>
            <select name="sort_mode" id="" class="form-control">
              <option value="0">Title</option>
              <option value="1">Recent</option>
            </select>
          </div>
          <button type="submit" class="btn btn-primary">Search</button>

      <% end %>
      <%= link_to "Recents", articles_path(sort_mode: "1"), class: 'btn btn-success', method: :get %>

    </div>

    <div class="row">
      rails table
        <table class="table">
          <thead>
            <tr>
                <th>#</th>
                <th>title</th>
                <th>content</th>
                <th>created at</th>
                <th>updated at</th>
                <th>actions</th>
            </tr>
          </thead>
          <tbody>
            <% @articles.each do |article| %>
            <tr >
                <td><%= article.id %></td>
                <td><%= article.title %></td>
                <td><%= article.content %></td>
                <td><%= article.created_at %></td>
                <td><%= article.updated_at %></td>
                <td>
                    <%= link_to "Show", article_path(article.id) %>
                    |
                    <%= link_to "Edit", edit_article_path(article.id) %>
                </td>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  <div class="row" >
    Javascript Table
    <div id="jsarticles"></div>
  </div>
  <div class="row">
    Rails AJAX Table
    <div id="rails-articles"></div>
  </div>
</div>

app/views/articles/index.js.erb
$("#rails-articles").html("<%= @articles.length %>")

app/views/articles/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="page-header">Article Index</h1>
  </div>
  <div class="row">
    <% if(flash[:error]) %>
      <div class="alert alert-danger" role="alert">
        <strong>Error</strong> <%= flash[:error]%>
      </div>
    <% end %>
  </div>
  <div class="row">
    <%= render "form" %>
  </div>
</div>

app/views/articles/show.html.erb
title: <%= @article.title %> <br/>
content: <%= @article.content %> <br/>

<% if(flash[:error]) %>
  <%= flash[:error]%>
<% end %>

<%= form_for [@article, @comment] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <br>
  <%= f.button %>
<% end %>

<% if @article.comments.count == 0 %>
<strong>No comments</strong>
<% else %>
Number of comments: <%= @article.comments.count %> <br/>

<strong>Comments</strong>
<ul>
<% @article.comments.each do |comment| %>
  <li><%= comment.id %> - <%= comment.content %></li>
<% end %>
</ul>

<% end %>

app/views/comment/create.html.erb
<h1>Comment#create</h1>
<p>Find me in app/views/comment/create.html.erb</p>

app/views/hello/index.html.erb
<%= form_tag("/hello", method: "post") do %>
  name: <input type="text" name="name" id="name" value="<%= @name %>"/> <br/>
  <button type="submit">Say Hello</button>
<% end %>
hello <%= @name %>

app/views/hello/say_hello.html.erb
hello <%= @name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper container-fluid">
      <div class="header row">
        <div class="col-md-12">
          <nav class="navbar navbar-light bg-faded">
            <a class="navbar-brand" href="#">Blog Application</a>
            <ul class="nav navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <%= link_to "Hello", hello_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "Articles", articles_path, class: 'nav-link' %>
              </li>
              <% if logged_in %>
              <li class="nav-item">
                <a href="#" class="nav-link"><%= current_user.name%></a>
              </li>
              <li class="nav-item">
                <%= link_to "Logout", logout_path, class: 'nav-link', method: :delete %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to "Login", login_path, class: 'nav-link'%>
              </li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
      <div class="content row">
        <div class="sidebar col-md-3">
          side bar
        </div>
        <div class="main-content col-md-9">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>